---
# main playbook

- hosts: spines, leafs
  gather_facts: false

  roles:
    - role: common
    - role: underlay

- hosts: leafs
  gather_facts: false

  roles:
    - role: overlay

- hosts: nxos
  gather_facts: false

  tasks:
    - name: Save Running-Config to Startup-Config
      cisco.nxos.nxos_config:
        save_when: always
