---
# vars file for S2

hostname: S2

layer3_physical_interfaces: &l3
    - interface: ethernet1/1
      description: To L1 Eth1/12
      ip_address: 10.2.2.0
      mask: 31
      mtu: 9216
    - interface: ethernet1/2
      description: To L2 Eth1/12
      ip_address: 10.2.2.2
      mask: 31
      mtu: 9216
    - interface: ethernet1/3
      description: To L3 Eth1/12
      ip_address: 10.2.2.4
      mask: 31
      mtu: 9216

loopback_interfaces: &lo
    - interface: loopback0 
      description: Routing Loopback
      ip_address: 10.0.0.2
      mask: 32
    - interface: loopback250
      description: PIM Anycast RP Loopback
      ip_address: 10.10.10.250
      mask: 32

all_layer3_interfaces:
    - *l3
    - *lo
