---
# vars file for spine1

hostname: spine1

layer3_physical_interfaces: &l3
    - interface: mgmt0
      ip_address: 10.15.34.11
      mask: 24
      mtu: 1500
    - interface: ethernet1/1
      description: To L1 Eth1/11
      ip_address: 10.1.1.0
      mask: 31
      mtu: 9216
    - interface: ethernet1/2
      description: To L2 Eth1/11
      ip_address: 10.1.1.2
      mask: 31
      mtu: 9216
    - interface: ethernet1/3
      description: To L3 Eth1/11
      ip_address: 10.1.1.4
      mask: 31
      mtu: 9216

loopback_interfaces: &lo
    - interface: loopback0 
      description: Routing Loopback
      ip_address: 10.0.0.1
      mask: 32
    - interface: loopback250
      description: PIM Anycast RP Loopback
      ip_address: 10.10.10.250
      mask: 32

all_layer3_interfaces:
    - *l3
    - *lo
