---
# tasks file for roles/fabric

- name: Role Entry Point - [create_fabric]
  ansible.builtin.debug:
    msg:
      - "----------------------------------------------------------------"
      - "+             Calling Role - [create_fabric]                   +"
      - "----------------------------------------------------------------"
  tags:
    - cf_vxlan
    - cf_all

- name: Create NDFC Fabric {{ fabric_settings.FABRIC_NAME }}
  cisco.dcnm.dcnm_fabric:
    config: ["{{ fabric_settings }}"]
    state: merged
  tags:
    - cf_vxlan
    - cf_all
