---

vrfs:
  - vrf_name: &refvrf_ansible AnsibleVRF
    vrf_id: 50003
    vlan_id: 2003
    attach_group: all_leaf
    deploy: false
networks:
  - net_name: AnsibleNet1
    vrf_name: *refvrf_ansible
    net_id: 30003
    vlan_id: 2303
    vlan_name: AnsibleNet1_vlan2303
    gw_ip_subnet: 10.3.3.1/24
    attach_group: esxi
    deploy: false
  - net_name: AnsibleNet2
    vrf_name: *refvrf_ansible
    net_id: 30004
    vlan_id: 2304
    vlan_name: AnsibleNet2_vlan2304
    gw_ip_subnet: 10.3.4.1/24
    attach_group: esxi
    deploy: false

vrf_attach_group:
  all_leaf:
    - ip_address: 10.15.33.13
    - ip_address: 10.15.33.14
    - ip_address: 10.15.33.15

net_attach_group:
  esxi:
    - ip_address: 10.15.33.13
      ports: [Ethernet1/11]
    - ip_address: 10.15.33.14
      ports: [Ethernet1/11]
    - ip_address: 10.15.33.15
      ports: [Ethernet1/11]
