---
# tasks file for roles/underlay

- name: Generate Interface Attributes Config Payload
  ansible.builtin.set_fact:
    nxos_interfaces: "{{ lookup('template', 'nxos_interfaces.j2') }}"

- name: Configure Interface Attributes
  cisco.nxos.nxos_interfaces:
    config: "{{ nxos_interfaces | from_yaml }}"
    state: merged

- name: Generate Interface L3 Config Payload
  ansible.builtin.set_fact:
    nxos_l3_interfaces: "{{ lookup('template', 'nxos_l3_interfaces.j2') }}"

- name: Configure L3 Interface Attributes
  cisco.nxos.nxos_l3_interfaces:
    config: "{{ nxos_l3_interfaces | from_yaml }}"
    state: merged

- name: Configure Underlay OSPF Process
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
      - process_id: "{{ ospf_process_id }}"
        router_id: "{{ loopback_interfaces[0].ip_address }}"
    state: merged

- name: Generate OSPF Interface Config Payload
  ansible.builtin.set_fact:
    nxos_ospf_interfaces: "{{ lookup('template', 'nxos_ospf_interfaces.j2') }}"

- name: Configure Interface Association to OSPF Process
  cisco.nxos.nxos_ospf_interfaces:
    config: "{{ nxos_ospf_interfaces | from_yaml }}"
    state: merged

- name: Configure PIM Anycast RP
  cisco.nxos.nxos_config:
    lines:
      - "ip pim anycast-rp {{ hostvars[groups['spines'][1]].loopback_interfaces[1].ip_address }} {{ hostvars[groups['spines'][1]].loopback_interfaces[0].ip_address }}"
      - "ip pim anycast-rp {{ hostvars[groups['spines'][2]].loopback_interfaces[1].ip_address }} {{ hostvars[groups['spines'][2]].loopback_interfaces[0].ip_address }}"
    save_when: modified
  when: inventory_hostname in groups['spines'] 

- name: Configure Interface Association to PIM Process
  cisco.nxos.nxos_pim_interface:
    interface: "{{ item.interface }}"
    sparse: true
    state: present
  loop: "{{ all_layer3_interfaces | flatten(1) }}"

- cisco.nxos.nxos_pim_rp_address:
    rp_address: "{{ hostvars[groups['spines'][1]].loopback_interfaces[1].ip_address }}"
    state: present

- name: Enable NV Overlay EVPN
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true

- name: Generate BGP Global & Neighbor Config Payload
  ansible.builtin.set_fact:
    nxos_bgp_global: "{{ lookup('template', 'nxos_bgp_global.j2') }}"

- name: Configure BGP Process and Neighbors
  cisco.nxos.nxos_bgp_global:
    config: "{{ nxos_bgp_global | from_yaml }}"
    state: merged

- name: Generate BGP Neighbor AF Config Payload
  ansible.builtin.set_fact:
    nxos_bgp_nbr_af: "{{ lookup('template', 'nxos_bgp_nbr_af.j2') }}"

- name: Configure BGP Neighbor Address-Families
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config: "{{ nxos_bgp_nbr_af | from_yaml }}"
    state: merged
